<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mohamad Boroumand">
<meta name="dcterms.date" content="2025-04-15">
<meta name="description" content="A simulation-based walkthrough of A/B testing through the lens of classical frequentist statistics — covering the Law of Large Numbers, bootstrap, CLT, hypothesis testing, regression equivalence, and the peeking problem.">

<title>A/B Testing a Call to Action – Mo Boroumand</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-3857c22e486953263cef44b5ce82424e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9aff62aabbafb588f71161e519e9e577.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles/custom.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Mo Boroumand</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../experience.html"> 
<span class="menu-text">Experience</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../products.html"> 
<span class="menu-text">Products</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../startup.html"> 
<span class="menu-text">Startup Ideas</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/moboroumand"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/moboroumand"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/moboroumand"> <i class="bi bi-twitter-x" role="img" aria-label="Twitter / X">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-ab-test-as-a-statistical-problem" id="toc-the-ab-test-as-a-statistical-problem" class="nav-link" data-scroll-target="#the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</a></li>
  <li><a href="#simulating-data" id="toc-simulating-data" class="nav-link" data-scroll-target="#simulating-data">Simulating Data</a></li>
  <li><a href="#the-law-of-large-numbers" id="toc-the-law-of-large-numbers" class="nav-link" data-scroll-target="#the-law-of-large-numbers">The Law of Large Numbers</a></li>
  <li><a href="#bootstrap-standard-errors" id="toc-bootstrap-standard-errors" class="nav-link" data-scroll-target="#bootstrap-standard-errors">Bootstrap Standard Errors</a></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem">The Central Limit Theorem</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#the-t-test-as-a-regression" id="toc-the-t-test-as-a-regression" class="nav-link" data-scroll-target="#the-t-test-as-a-regression">The T-Test as a Regression</a></li>
  <li><a href="#the-problem-with-peeking" id="toc-the-problem-with-peeking" class="nav-link" data-scroll-target="#the-problem-with-peeking">The Problem with Peeking</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">A/B Testing a Call to Action</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Simulating Key Ideas from Classical Frequentist Statistics</p>
  <div class="quarto-categories">
    <div class="quarto-category">statistics</div>
    <div class="quarto-category">python</div>
    <div class="quarto-category">A/B testing</div>
    <div class="quarto-category">data science</div>
  </div>
  </div>

<div>
  <div class="description">
    A simulation-based walkthrough of A/B testing through the lens of classical frequentist statistics — covering the Law of Large Numbers, bootstrap, CLT, hypothesis testing, regression equivalence, and the peeking problem.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mohamad Boroumand </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Imagine you run a small online publication. Your homepage has a simple sign-up form where visitors can subscribe to your newsletter, and right above that form sits a short line of text — a <em>call to action</em> (CTA) — designed to nudge people into clicking. You have two versions in mind:</p>
<ul>
<li><strong>CTA A:</strong> <em>“Sign up for our newsletter here!”</em></li>
<li><strong>CTA B:</strong> <em>“Stay up to date by signing up!”</em></li>
</ul>
<p>Both convey the same message, but wording can matter more than intuition suggests. The question is: does one outperform the other in converting casual visitors into subscribers?</p>
<p>To find out, we run an <strong>A/B test</strong>. Each time a new visitor lands on the homepage, we randomly assign them to see either CTA A or CTA B — like flipping a fair coin on every visit. Once we have gathered data from enough visitors, we compare the sign-up rates between the two groups. Randomization is the key ingredient: it ensures that any difference we observe in sign-up rates is attributable to the CTA itself, rather than to some confounding factor such as time of day, device type, or traffic source.</p>
<p>In this post, we walk through the core ideas of classical frequentist statistics by working through this A/B test from the ground up — simulating data, visualizing the Law of Large Numbers, bootstrapping confidence intervals, demonstrating the Central Limit Theorem, performing a hypothesis test, connecting that test to linear regression, and finally showing what goes wrong when you peek at your results too early.</p>
</section>
<section id="the-ab-test-as-a-statistical-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</h2>
<p>At the individual level, every visitor either signs up (outcome = 1) or does not (outcome = 0). This binary trial is exactly the setting modeled by a <strong>Bernoulli distribution</strong>: a single flip of a coin whose probability of heads is some unknown parameter <span class="math inline">\(\pi\)</span>. We write:</p>
<p><span class="math display">\[X_i^A \sim \text{Bernoulli}(\pi_A) \qquad X_i^B \sim \text{Bernoulli}(\pi_B)\]</span></p>
<p>where <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span> are the true (unknown) sign-up probabilities under each CTA. The whole purpose of the experiment is to learn about these parameters from data.</p>
<p>The <strong>quantity we care about</strong> is the difference in sign-up rates:</p>
<p><span class="math display">\[\theta = \pi_A - \pi_B\]</span></p>
<p>If <span class="math inline">\(\theta &gt; 0\)</span>, CTA A converts better; if <span class="math inline">\(\theta &lt; 0\)</span>, CTA B wins; if <span class="math inline">\(\theta = 0\)</span>, the choice of wording makes no difference.</p>
<p>Since <span class="math inline">\(\theta\)</span> is unobservable, we estimate it with the <strong>difference in sample proportions</strong>:</p>
<p><span class="math display">\[\hat\theta = \bar{X}_A - \bar{X}_B = \hat\pi_A - \hat\pi_B\]</span></p>
<p>Because each observation is either 0 or 1, the sample mean is just the fraction of visitors who signed up — so the two expressions are identical. This estimator is our best guess at <span class="math inline">\(\theta\)</span> given the data we collect.</p>
<p>The sections that follow explore how reliable this estimator is, how uncertain we should be about it, and how to use it to reach a statistically rigorous decision.</p>
</section>
<section id="simulating-data" class="level2">
<h2 class="anchored" data-anchor-id="simulating-data">Simulating Data</h2>
<p>In a real experiment we would never know the true values of <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span> — estimating them is precisely why we run the test. But for the purpose of this walkthrough, we set them ourselves so we can study how our estimator behaves when we know the ground truth.</p>
<p>We assume:</p>
<p><span class="math display">\[\pi_A = 0.22, \quad \pi_B = 0.18, \quad \theta = \pi_A - \pi_B = 0.04\]</span></p>
<p>So CTA A has a genuine four-percentage-point advantage. We simulate 1,000 visitor outcomes for each group (2,000 total).</p>
<div id="998c9c99" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>pi_A       <span class="op">=</span> <span class="fl">0.22</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pi_B       <span class="op">=</span> <span class="fl">0.18</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>true_theta <span class="op">=</span> pi_A <span class="op">-</span> pi_B   <span class="co"># 0.04</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>n          <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate visitor outcomes: 1 = signed up, 0 = did not</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_A, n)   <span class="co"># CTA A group</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_B, n)   <span class="co"># CTA B group</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>pi_A_hat  <span class="op">=</span> A.mean()</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>pi_B_hat  <span class="op">=</span> B.mean()</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>theta_hat <span class="op">=</span> pi_A_hat <span class="op">-</span> pi_B_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="85502bbe" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_e18ec th {
  background-color: #2a7abf;
  color: white;
  font-weight: bold;
  padding: 8px 14px;
}
#T_e18ec td {
  padding: 7px 14px;
}
#T_e18ec tr:nth-child(even) {
  background-color: #eef4fb;
}
#T_e18ec  {
  border-collapse: collapse;
  font-size: 0.93em;
}
</style>

<div id="T_e18ec" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_e18ec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Simulated Data Summary
</figcaption>
<div aria-describedby="T_e18ec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_e18ec" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_e18ec_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Group</th>
<th id="T_e18ec_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">True Value</th>
<th id="T_e18ec_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Observed in Simulation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_e18ec_row0_col0" class="data row0 col0">CTA A</td>
<td id="T_e18ec_row0_col1" class="data row0 col1">π_A = 0.22</td>
<td id="T_e18ec_row0_col2" class="data row0 col2">0.2160</td>
</tr>
<tr class="even">
<td id="T_e18ec_row1_col0" class="data row1 col0">CTA B</td>
<td id="T_e18ec_row1_col1" class="data row1 col1">π_B = 0.18</td>
<td id="T_e18ec_row1_col2" class="data row1 col2">0.1780</td>
</tr>
<tr class="odd">
<td id="T_e18ec_row2_col0" class="data row2 col0">Difference (θ̂)</td>
<td id="T_e18ec_row2_col1" class="data row2 col1">θ = 0.04000000000000001</td>
<td id="T_e18ec_row2_col2" class="data row2 col2">0.0380</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>Our estimate <span class="math inline">\(\hat\theta \approx\)</span> np.float64(0.038) lands close to the true value of 0.04. The sections below explore <em>why</em> we can trust it, <em>how precise</em> it is, and <em>when</em> it is large enough to be statistically significant.</p>
</section>
<section id="the-law-of-large-numbers" class="level2">
<h2 class="anchored" data-anchor-id="the-law-of-large-numbers">The Law of Large Numbers</h2>
<p>How do we know that <span class="math inline">\(\hat\theta = \bar{X}_A - \bar{X}_B\)</span> is a sensible estimator of <span class="math inline">\(\theta\)</span>? The mathematical guarantee comes from the <strong>Law of Large Numbers (LLN)</strong>: as the number of observations grows, the sample mean converges to the population mean. Since <span class="math inline">\(\hat\pi_A \to \pi_A\)</span> and <span class="math inline">\(\hat\pi_B \to \pi_B\)</span>, it follows that <span class="math inline">\(\hat\theta \to \theta\)</span>.</p>
<p>The LLN is the foundational reason why running a <em>larger</em> experiment gives you a <em>more reliable</em> answer. But how fast does convergence happen? The plot below makes it concrete.</p>
<p>We compute the <strong>element-wise differences</strong> between CTA A and CTA B draws and track the <strong>running (cumulative) mean</strong> as we add one observation at a time.</p>
<div id="15880cac" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Element-wise differences between paired draws</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>diffs <span class="op">=</span> A <span class="op">-</span> B   <span class="co"># length-1000 vector</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Running mean: average of first 1, first 2, …, first 1000 differences</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>running_mean <span class="op">=</span> np.cumsum(diffs) <span class="op">/</span> np.arange(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-fig-lln" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">4.5</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>ax.plot(<span class="bu">range</span>(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>), running_mean,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="fl">1.6</span>, alpha<span class="op">=</span><span class="fl">0.9</span>, label<span class="op">=</span><span class="vs">r"Running mean of </span><span class="dv">$</span><span class="vs">X_A - X_B</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>ax.axhline(true_theta, color<span class="op">=</span>RED, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"True θ = </span><span class="sc">{</span>true_theta<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>ax.fill_between(<span class="bu">range</span>(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                true_theta <span class="op">-</span> <span class="fl">0.015</span>, true_theta <span class="op">+</span> <span class="fl">0.015</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                alpha<span class="op">=</span><span class="fl">0.12</span>, color<span class="op">=</span>RED)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Number of Observations"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Running Mean of Differences"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Law of Large Numbers: Convergence of $</span><span class="ch">\\</span><span class="st">hat{</span><span class="ch">\\</span><span class="st">theta}$ Toward the True $</span><span class="ch">\\</span><span class="st">theta$"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">True</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">1</span>, n)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-lln" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lln-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-lln-output-1.png" width="1189" height="526" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lln-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The running mean starts noisy but settles toward the true θ = 0.04 as the sample grows.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The plot tells a clear story. With only a handful of observations the running mean swings wildly — a few lucky sign-ups in one group can send the estimate far from the truth. But as the sample grows, those fluctuations dampen. By around 200–300 observations the curve has largely settled near 0.04, and by 1,000 observations it is hugging the true value closely.</p>
<p>This is the LLN in action: <strong>more data means less noise</strong>. It is the foundational reason why running a larger experiment gives a more reliable answer than running a small one.</p>
</section>
<section id="bootstrap-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="bootstrap-standard-errors">Bootstrap Standard Errors</h2>
<p>The LLN tells us our estimator will eventually get close to the truth, but “eventually” is not a precision statement. A practicing analyst also needs a measure of <strong>uncertainty</strong>: how far from the truth is <span class="math inline">\(\hat\theta\)</span> likely to be with the sample we actually have?</p>
<p>One elegant approach is the <strong>bootstrap</strong>. The idea is deceptively simple: if we could re-run our experiment many times under identical conditions, we could directly observe how much <span class="math inline">\(\hat\theta\)</span> varies from run to run. We cannot actually re-run the experiment, but we can <em>simulate</em> repeated experiments by <strong>resampling with replacement</strong> from the data we already have.</p>
<p>The procedure:</p>
<ol type="1">
<li>Draw 1,000 samples with replacement from the CTA A data (<span class="math inline">\(A^*\)</span>) and independently from the CTA B data (<span class="math inline">\(B^*\)</span>).</li>
<li>Compute <span class="math inline">\(\hat\theta^* = \bar{X}_{A}^* - \bar{X}_{B}^*\)</span> for that resample.</li>
<li>Repeat 1,000 times.</li>
<li>The standard deviation of those 1,000 bootstrapped estimates is the <strong>bootstrapped standard error</strong>.</li>
</ol>
<div id="f0f20110" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>B_reps <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>boot_thetas <span class="op">=</span> np.array([</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    np.random.choice(A, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>).mean() <span class="op">-</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    np.random.choice(B, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>).mean()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(B_reps)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>se_boot <span class="op">=</span> boot_thetas.std()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Closed-form analytical SE for difference in two independent proportions</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>se_analytical <span class="op">=</span> np.sqrt(</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    pi_A_hat <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_A_hat) <span class="op">/</span> n <span class="op">+</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    pi_B_hat <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_B_hat) <span class="op">/</span> n</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% confidence interval using the bootstrapped SE (normal approximation)</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>ci_lo_boot <span class="op">=</span> theta_hat <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se_boot</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>ci_hi_boot <span class="op">=</span> theta_hat <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se_boot</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>ci_lo_anal <span class="op">=</span> theta_hat <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se_analytical</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>ci_hi_anal <span class="op">=</span> theta_hat <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se_analytical</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="4522046f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_c0aff th {
  background-color: #2a7abf;
  color: white;
  font-weight: bold;
  padding: 8px 14px;
}
#T_c0aff td {
  padding: 7px 14px;
}
#T_c0aff tr:nth-child(even) {
  background-color: #eef4fb;
}
#T_c0aff  {
  border-collapse: collapse;
  font-size: 0.93em;
}
</style>

<div id="T_c0aff" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_c0aff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Standard Error Comparison: Bootstrap vs. Analytical
</figcaption>
<div aria-describedby="T_c0aff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_c0aff" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_c0aff_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Method</th>
<th id="T_c0aff_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Standard Error</th>
<th id="T_c0aff_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">95% CI Lower</th>
<th id="T_c0aff_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_c0aff_row0_col0" class="data row0 col0">Bootstrap</td>
<td id="T_c0aff_row0_col1" class="data row0 col1">0.01765</td>
<td id="T_c0aff_row0_col2" class="data row0 col2">0.0034</td>
<td id="T_c0aff_row0_col3" class="data row0 col3">0.0726</td>
</tr>
<tr class="even">
<td id="T_c0aff_row1_col0" class="data row1 col0">Analytical formula</td>
<td id="T_c0aff_row1_col1" class="data row1 col1">0.01777</td>
<td id="T_c0aff_row1_col2" class="data row1 col2">0.0032</td>
<td id="T_c0aff_row1_col3" class="data row1 col3">0.0728</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>The two standard errors are nearly identical — which is exactly what we should hope to see. The bootstrap is recovering the same precision estimate as the closed-form formula, without requiring us to know that formula in advance. This is the real power of the bootstrap: <strong>it works equally well regardless of how complicated your estimator is</strong>.</p>
<p><strong>Interpreting the confidence interval:</strong> We are 95% confident that the true difference <span class="math inline">\(\theta = \pi_A - \pi_B\)</span> lies between np.float64(0.0034) and np.float64(0.0726). Since this interval sits entirely above zero, it provides evidence that CTA A genuinely outperforms CTA B — and not merely by chance.</p>
</section>
<section id="the-central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="the-central-limit-theorem">The Central Limit Theorem</h2>
<p>We now know our estimator converges (LLN) and that we can measure its variability (bootstrap). But to do formal hypothesis testing, we need to know the <em>shape</em> of the estimator’s sampling distribution — not just its center and spread.</p>
<p>The <strong>Central Limit Theorem (CLT)</strong> provides this. It states that regardless of what distribution the underlying data follow, the sampling distribution of the sample mean becomes approximately <strong>Normal</strong> as the sample size grows. Since <span class="math inline">\(\hat\theta = \bar{X}_A - \bar{X}_B\)</span> is the difference of two sample means — and the difference of two independent Normals is itself Normal — the CLT applies directly to our estimator.</p>
<p>To see this in action, we simulate 1,000 experiments at each of four sample sizes, <span class="math inline">\(n \in \{25, 50, 100, 500\}\)</span>, and plot the resulting distribution of <span class="math inline">\(\hat\theta\)</span>.</p>
<div id="cell-fig-clt" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-clt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-clt-output-1.png" width="1428" height="1014" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: As sample size grows, the sampling distribution of θ̂ becomes smoother and more bell-shaped. The dashed curve is the best-fit Normal; the red line marks the true θ = 0.04.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The progression is striking. At <span class="math inline">\(n = 25\)</span>, the histogram is lumpy and slightly asymmetric — with such small samples the discrete Bernoulli nature of the data is still visible. By <span class="math inline">\(n = 100\)</span>, the distribution has smoothed out considerably and the Normal approximation (dashed curve) is already reasonable. At <span class="math inline">\(n = 500\)</span>, the histogram is nearly indistinguishable from a true Normal distribution.</p>
<p>Notice also that the spread shrinks as <span class="math inline">\(n\)</span> grows — the LLN and CLT working in tandem. Larger samples yield estimates that are both more accurate <em>and</em> more tightly concentrated around the truth. The CLT is what licenses us to use Normal-based formulas (z-statistics, p-values) for inference in the sections that follow.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<p>Now that we know <span class="math inline">\(\hat\theta\)</span> is approximately Normally distributed for large samples, we can ask the formal question: <strong>Is the difference we observed large enough to rule out random chance?</strong></p>
<p>This is the logic of <strong>hypothesis testing</strong>. We begin by assuming the most skeptical position — that there is no difference between the two CTAs — and ask whether the data are inconsistent with that assumption.</p>
<p><span class="math display">\[H_0: \theta = 0 \quad \text{(no difference)} \qquad H_1: \theta \neq 0 \quad \text{(some difference)}\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the CLT tells us <span class="math inline">\(\hat\theta \approx N(0, \text{SE}(\hat\theta))\)</span>. To assess how unusual our observed <span class="math inline">\(\hat\theta\)</span> is, we <strong>standardize</strong> it:</p>
<p><span class="math display">\[z = \frac{\hat\theta - 0}{\text{SE}(\hat\theta)}\]</span></p>
<p>After standardization, <span class="math inline">\(z\)</span> follows approximately a standard Normal <span class="math inline">\(N(0, 1)\)</span> under <span class="math inline">\(H_0\)</span>. The <strong>p-value</strong> is the probability of observing a <span class="math inline">\(|z|\)</span> as large as ours (or larger) if the null were actually true. A small p-value means our data would be very surprising under <span class="math inline">\(H_0\)</span> — strong reason to doubt it.</p>
<blockquote class="blockquote">
<p><strong>Why “t-test” if we’re using the Normal?</strong> In the classical t-test, the data themselves are assumed Normal and the variance must be estimated — the resulting ratio then follows an exact t-distribution. Here, our data are Bernoulli (binary), so there is no exact t-distribution result. The CLT gives us approximate Normality, and what we are doing is technically a <strong>z-test</strong>. In practice, for large samples the t-distribution converges to the standard Normal, so the distinction rarely matters numerically — but it is important to understand conceptually why.</p>
</blockquote>
<div id="1d8a3f23" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>z_stat  <span class="op">=</span> theta_hat <span class="op">/</span> se_analytical</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(<span class="bu">abs</span>(z_stat)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="4cbfcc09" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_8e784 th {
  background-color: #2a7abf;
  color: white;
  font-weight: bold;
  padding: 8px 14px;
}
#T_8e784 td {
  padding: 7px 14px;
}
#T_8e784 tr:nth-child(even) {
  background-color: #eef4fb;
}
#T_8e784  {
  border-collapse: collapse;
  font-size: 0.93em;
}
</style>

<div id="T_8e784" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_8e784-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Two-Sample Z-Test Results
</figcaption>
<div aria-describedby="T_8e784-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_8e784" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_8e784_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Quantity</th>
<th id="T_8e784_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_8e784_row0_col0" class="data row0 col0">Estimated difference (θ̂)</td>
<td id="T_8e784_row0_col1" class="data row0 col1">0.0380</td>
</tr>
<tr class="even">
<td id="T_8e784_row1_col0" class="data row1 col0">Standard error SE(θ̂)</td>
<td id="T_8e784_row1_col1" class="data row1 col1">0.0178</td>
</tr>
<tr class="odd">
<td id="T_8e784_row2_col0" class="data row2 col0">z-statistic</td>
<td id="T_8e784_row2_col1" class="data row2 col1">2.1388</td>
</tr>
<tr class="even">
<td id="T_8e784_row3_col0" class="data row3 col0">p-value</td>
<td id="T_8e784_row3_col1" class="data row3 col1">0.0325</td>
</tr>
<tr class="odd">
<td id="T_8e784_row4_col0" class="data row4 col0">Significant at α = 0.05?</td>
<td id="T_8e784_row4_col1" class="data row4 col1">Yes</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>With a p-value of np.float64(0.0325) — well below the conventional 0.05 threshold — we <strong>reject the null hypothesis</strong>. The data provide strong statistical evidence that CTA A and CTA B produce different sign-up rates, confirming the four-percentage-point advantage we built into the simulation.</p>
</section>
<section id="the-t-test-as-a-regression" class="level2">
<h2 class="anchored" data-anchor-id="the-t-test-as-a-regression">The T-Test as a Regression</h2>
<p>There is an elegant algebraic fact hidden beneath the two-sample test: <strong>it is mathematically equivalent to a simple linear regression</strong>. Understanding this connection matters because the regression framework generalizes naturally — you can add control variables, interaction terms, or additional treatment arms — while producing identical inference in the simple two-group case.</p>
<p>The setup is straightforward. We stack all 2,000 observations into a single dataset with two columns:</p>
<ul>
<li><span class="math inline">\(Y_i\)</span>: 1 if visitor <span class="math inline">\(i\)</span> signed up, 0 otherwise</li>
<li><span class="math inline">\(D_i\)</span>: 1 if visitor <span class="math inline">\(i\)</span> saw CTA A, 0 if they saw CTA B</li>
</ul>
<p>We then fit:</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 D_i + \varepsilon_i\]</span></p>
<p>The OLS estimates have an immediate interpretation:</p>
<ul>
<li><span class="math inline">\(\hat\beta_0\)</span> is the expected <span class="math inline">\(Y_i\)</span> when <span class="math inline">\(D_i = 0\)</span> (CTA B) — i.e., <span class="math inline">\(\hat\beta_0 = \hat\pi_B\)</span>.</li>
<li><span class="math inline">\(\hat\beta_0 + \hat\beta_1\)</span> is the expected <span class="math inline">\(Y_i\)</span> when <span class="math inline">\(D_i = 1\)</span> (CTA A) — i.e., <span class="math inline">\(\hat\beta_0 + \hat\beta_1 = \hat\pi_A\)</span>.</li>
<li>Therefore <span class="math inline">\(\hat\beta_1 = \hat\pi_A - \hat\pi_B = \hat\theta\)</span> — numerically identical to our earlier estimator.</li>
</ul>
<div id="d5a8dd79" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> np.concatenate([A, B])</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> np.concatenate([np.ones(n), np.zeros(n)])   <span class="co"># 1 = CTA A, 0 = CTA B</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(D)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>ols_model <span class="op">=</span> sm.OLS(Y, X).fit()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="b7231b93" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_9be44 th {
  background-color: #2a7abf;
  color: white;
  font-weight: bold;
  padding: 8px 14px;
}
#T_9be44 td {
  padding: 7px 14px;
}
#T_9be44 tr:nth-child(even) {
  background-color: #eef4fb;
}
#T_9be44  {
  border-collapse: collapse;
  font-size: 0.93em;
}
</style>

<div id="T_9be44" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_9be44-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: OLS Regression Coefficients
</figcaption>
<div aria-describedby="T_9be44-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_9be44" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_9be44_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Term</th>
<th id="T_9be44_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Estimate</th>
<th id="T_9be44_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Std. Error</th>
<th id="T_9be44_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">t-statistic</th>
<th id="T_9be44_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_9be44_row0_col0" class="data row0 col0">Intercept (β₀)</td>
<td id="T_9be44_row0_col1" class="data row0 col1">0.1780</td>
<td id="T_9be44_row0_col2" class="data row0 col2">0.0126</td>
<td id="T_9be44_row0_col3" class="data row0 col3">14.1615</td>
<td id="T_9be44_row0_col4" class="data row0 col4">0.0000</td>
</tr>
<tr class="even">
<td id="T_9be44_row1_col0" class="data row1 col0">CTA A Indicator (β₁)</td>
<td id="T_9be44_row1_col1" class="data row1 col1">0.0380</td>
<td id="T_9be44_row1_col2" class="data row1 col2">0.0178</td>
<td id="T_9be44_row1_col3" class="data row1 col3">2.1377</td>
<td id="T_9be44_row1_col4" class="data row1 col4">0.0327</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>Look at the row for <span class="math inline">\(\hat\beta_1\)</span>: the estimate, standard error, and p-value are essentially identical to the values we computed using the two-sample approach. The small numerical difference arises because standard OLS assumes a <strong>pooled variance</strong> across both groups, while our two-sample formula used <strong>separate variance estimates</strong> for each group. For large samples of equal size, the difference is negligible.</p>
<p>The intercept <span class="math inline">\(\hat\beta_0 \approx\)</span> np.float64(0.178) estimates <span class="math inline">\(\pi_B\)</span> (the CTA B sign-up rate), and <span class="math inline">\(\hat\beta_0 + \hat\beta_1 \approx\)</span> np.float64(0.216) estimates <span class="math inline">\(\pi_A\)</span> — both very close to the true values of 0.18 and 0.22.</p>
<p>The regression framework is therefore not just an alternative way to run the same test — it is the foundation for everything more complex that comes after.</p>
</section>
<section id="the-problem-with-peeking" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-with-peeking">The Problem with Peeking</h2>
<p>Everything we have done so far assumes the experiment runs to completion before we look at the results. But what if someone gets impatient?</p>
<p>Suppose your boss wants to check in after every 100 visitors per group — at <span class="math inline">\(n = 100, 200, \ldots, 1000\)</span> — and declare a winner as soon as any single test comes back significant at <span class="math inline">\(\alpha = 0.05\)</span>. This practice is called <strong>peeking</strong>, and it quietly destroys the statistical properties of the test.</p>
<p>Here is why. A single test at <span class="math inline">\(\alpha = 0.05\)</span> has a 5% chance of a <strong>false positive</strong> — rejecting <span class="math inline">\(H_0\)</span> when it is actually true. But each peek at accumulating data creates another independent opportunity to get unlucky. The overall probability of at least one false positive across all 10 peeks is much higher than 5%, even if the two CTAs are genuinely identical.</p>
<p>We can measure exactly how much higher with a simulation. We set up a world where <strong>the null is true</strong> (<span class="math inline">\(\pi_A = \pi_B = 0.20\)</span>, no real difference), run 10,000 simulated experiments, and record in what fraction of those experiments peeking produces at least one spurious significant result.</p>
<div id="b7e4014e" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">123</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>pi_null       <span class="op">=</span> <span class="fl">0.20</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>n_total       <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>checkpoints   <span class="op">=</span> np.arange(<span class="dv">100</span>, <span class="dv">1001</span>, <span class="dv">100</span>)   <span class="co"># peek at 100, 200, …, 1000</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>n_experiments <span class="op">=</span> <span class="dv">10_000</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>false_positives <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_experiments):</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    A_null <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_null, n_total)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    B_null <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_null, n_total)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> cp <span class="kw">in</span> checkpoints:</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>        a_sub <span class="op">=</span> A_null[:cp]</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        b_sub <span class="op">=</span> B_null[:cp]</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        pa <span class="op">=</span> a_sub.mean()</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>        pb <span class="op">=</span> b_sub.mean()</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        diff <span class="op">=</span> pa <span class="op">-</span> pb</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        se_sub <span class="op">=</span> np.sqrt(pa <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pa) <span class="op">/</span> cp <span class="op">+</span> pb <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pb) <span class="op">/</span> cp)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> se_sub <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>        z_sub <span class="op">=</span> diff <span class="op">/</span> se_sub</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>        p_sub <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(<span class="bu">abs</span>(z_sub)))</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p_sub <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>            false_positives <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span>   <span class="co"># boss declares a winner and stops the experiment</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>fpr <span class="op">=</span> false_positives <span class="op">/</span> n_experiments</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="0083448f" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_a82ac th {
  background-color: #c0392b;
  color: white;
  font-weight: bold;
  padding: 8px 14px;
}
#T_a82ac td {
  padding: 7px 14px;
}
#T_a82ac tr:nth-child(even) {
  background-color: #eef4fb;
}
#T_a82ac  {
  border-collapse: collapse;
  font-size: 0.93em;
}
</style>

<div id="T_a82ac" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_a82ac-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: False Positive Rate: Single Test vs. Sequential Peeking
</figcaption>
<div aria-describedby="T_a82ac-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_a82ac" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_a82ac_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Approach</th>
<th id="T_a82ac_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">False Positive Rate</th>
<th id="T_a82ac_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Inflation vs. Nominal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_a82ac_row0_col0" class="data row0 col0">Single pre-planned test (correct practice)</td>
<td id="T_a82ac_row0_col1" class="data row0 col1">~5.0%</td>
<td id="T_a82ac_row0_col2" class="data row0 col2">1.0×</td>
</tr>
<tr class="even">
<td id="T_a82ac_row1_col0" class="data row1 col0">Peek after every 100 visitors (10 peeks)</td>
<td id="T_a82ac_row1_col1" class="data row1 col1">~19.9%</td>
<td id="T_a82ac_row1_col2" class="data row1 col2">4.0×</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<div id="cell-fig-peeking" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div id="fig-peeking" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-peeking-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-peeking-output-1.png" width="828" height="523" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-peeking-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: A single pre-planned test holds the false positive rate at 5%. Sequential peeking inflates it to roughly 26% — more than five times the nominal level.
</figcaption>
</figure>
</div>
</div>
</div>
<p>With 10 peeks, the false positive rate balloons to roughly <strong>20%</strong> — more than five times the nominal 5%. That means more than one in four experiments produces a false alarm, even when the two CTAs are absolutely identical in effectiveness.</p>
<p>This is not a subtle theoretical quirk. It is a practical pitfall that has led to real-world product decisions being made on illusory results. The standard remedies include:</p>
<ul>
<li><strong>Pre-registering</strong> your sample size and running exactly one final test,</li>
<li>Using <strong>sequential testing</strong> methods (such as the Bonferroni correction or alpha-spending functions) that are designed to allow interim looks while still controlling the false positive rate, or</li>
<li>Adopting a <strong>Bayesian</strong> framework, which naturally incorporates accumulating evidence without inflating Type I error.</li>
</ul>
<p>The bottom line: in frequentist A/B testing, a p-value only means what it says — a 5% false positive rate — if you decide the sample size in advance and run the test exactly once. Everything else is a departure from that guarantee, and the consequences can be severe.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "A/B Testing a Call to Action"</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Simulating Key Ideas from Classical Frequentist Statistics"</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Mohamad Boroumand"</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2025-04-15"</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "A simulation-based walkthrough of A/B testing through the lens of classical frequentist statistics — covering the Law of Large Numbers, bootstrap, CLT, hypothesis testing, regression equivalence, and the peeking problem."</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [statistics, python, A/B testing, data science]</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> "../../assets/ab-test-preview.png"</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 2</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Contents"</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: flatly</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="co">    highlight-style: github</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.lines <span class="im">import</span> Line2D</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Global matplotlib style ──────────────────────────────────────────────────</span></span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figure.facecolor"</span>: <span class="st">"white"</span>,</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.facecolor"</span>: <span class="st">"#f7f7f7"</span>,</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.grid"</span>: <span class="va">True</span>,</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grid.color"</span>: <span class="st">"white"</span>,</span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grid.linewidth"</span>: <span class="fl">1.1</span>,</span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">"font.family"</span>: <span class="st">"sans-serif"</span>,</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.top"</span>: <span class="va">False</span>,</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.right"</span>: <span class="va">False</span>,</span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.labelsize"</span>: <span class="dv">11</span>,</span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.titlesize"</span>: <span class="dv">13</span>,</span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.titleweight"</span>: <span class="st">"bold"</span>,</span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a>    <span class="st">"xtick.labelsize"</span>: <span class="dv">10</span>,</span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ytick.labelsize"</span>: <span class="dv">10</span>,</span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figure.dpi"</span>: <span class="dv">120</span>,</span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a>BLUE    <span class="op">=</span> <span class="st">"#2a7abf"</span></span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a>ORANGE  <span class="op">=</span> <span class="st">"#e07b39"</span></span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a>RED     <span class="op">=</span> <span class="st">"#e63946"</span></span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a>GREEN   <span class="op">=</span> <span class="st">"#2ca02c"</span></span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a>PURPLE  <span class="op">=</span> <span class="st">"#9467bd"</span></span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a>PALETTE <span class="op">=</span> [BLUE, ORANGE, GREEN, PURPLE]</span>
<span id="cb8-62"><a href="#cb8-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-63"><a href="#cb8-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-64"><a href="#cb8-64" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Shared helper for styled pandas tables ───────────────────────────────────</span></span>
<span id="cb8-65"><a href="#cb8-65" aria-hidden="true" tabindex="-1"></a>_HDR <span class="op">=</span> [(<span class="st">"background-color"</span>, <span class="st">"#2a7abf"</span>), (<span class="st">"color"</span>, <span class="st">"white"</span>),</span>
<span id="cb8-66"><a href="#cb8-66" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"font-weight"</span>, <span class="st">"bold"</span>), (<span class="st">"padding"</span>, <span class="st">"8px 14px"</span>)]</span>
<span id="cb8-67"><a href="#cb8-67" aria-hidden="true" tabindex="-1"></a>_ROW <span class="op">=</span> [(<span class="st">"padding"</span>, <span class="st">"7px 14px"</span>)]</span>
<span id="cb8-68"><a href="#cb8-68" aria-hidden="true" tabindex="-1"></a>_ALT <span class="op">=</span> [(<span class="st">"background-color"</span>, <span class="st">"#eef4fb"</span>)]</span>
<span id="cb8-69"><a href="#cb8-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-70"><a href="#cb8-70" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> styled_table(df, caption<span class="op">=</span><span class="st">""</span>, hdr_color<span class="op">=</span><span class="st">"#2a7abf"</span>):</span>
<span id="cb8-71"><a href="#cb8-71" aria-hidden="true" tabindex="-1"></a>    hdr <span class="op">=</span> [(<span class="st">"background-color"</span>, hdr_color), (<span class="st">"color"</span>, <span class="st">"white"</span>),</span>
<span id="cb8-72"><a href="#cb8-72" aria-hidden="true" tabindex="-1"></a>           (<span class="st">"font-weight"</span>, <span class="st">"bold"</span>), (<span class="st">"padding"</span>, <span class="st">"8px 14px"</span>)]</span>
<span id="cb8-73"><a href="#cb8-73" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (</span>
<span id="cb8-74"><a href="#cb8-74" aria-hidden="true" tabindex="-1"></a>        df.style</span>
<span id="cb8-75"><a href="#cb8-75" aria-hidden="true" tabindex="-1"></a>          .set_table_styles([</span>
<span id="cb8-76"><a href="#cb8-76" aria-hidden="true" tabindex="-1"></a>              {<span class="st">"selector"</span>: <span class="st">"th"</span>, <span class="st">"props"</span>: hdr},</span>
<span id="cb8-77"><a href="#cb8-77" aria-hidden="true" tabindex="-1"></a>              {<span class="st">"selector"</span>: <span class="st">"td"</span>, <span class="st">"props"</span>: _ROW},</span>
<span id="cb8-78"><a href="#cb8-78" aria-hidden="true" tabindex="-1"></a>              {<span class="st">"selector"</span>: <span class="st">"tr:nth-child(even)"</span>, <span class="st">"props"</span>: _ALT},</span>
<span id="cb8-79"><a href="#cb8-79" aria-hidden="true" tabindex="-1"></a>              {<span class="st">"selector"</span>: <span class="st">""</span>, <span class="st">"props"</span>: [(<span class="st">"border-collapse"</span>, <span class="st">"collapse"</span>),</span>
<span id="cb8-80"><a href="#cb8-80" aria-hidden="true" tabindex="-1"></a>                                         (<span class="st">"font-size"</span>, <span class="st">"0.93em"</span>)]},</span>
<span id="cb8-81"><a href="#cb8-81" aria-hidden="true" tabindex="-1"></a>          ])</span>
<span id="cb8-82"><a href="#cb8-82" aria-hidden="true" tabindex="-1"></a>          .set_caption(caption)</span>
<span id="cb8-83"><a href="#cb8-83" aria-hidden="true" tabindex="-1"></a>          .hide(axis<span class="op">=</span><span class="st">"index"</span>)</span>
<span id="cb8-84"><a href="#cb8-84" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-85"><a href="#cb8-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-86"><a href="#cb8-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-87"><a href="#cb8-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-88"><a href="#cb8-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb8-89"><a href="#cb8-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-90"><a href="#cb8-90" aria-hidden="true" tabindex="-1"></a>Imagine you run a small online publication. Your homepage has a simple sign-up form where visitors can subscribe to your newsletter, and right above that form sits a short line of text — a *call to action* (CTA) — designed to nudge people into clicking. You have two versions in mind:</span>
<span id="cb8-91"><a href="#cb8-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-92"><a href="#cb8-92" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**CTA A:** *"Sign up for our newsletter here!"*</span>
<span id="cb8-93"><a href="#cb8-93" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**CTA B:** *"Stay up to date by signing up!"*</span>
<span id="cb8-94"><a href="#cb8-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-95"><a href="#cb8-95" aria-hidden="true" tabindex="-1"></a>Both convey the same message, but wording can matter more than intuition suggests. The question is: does one outperform the other in converting casual visitors into subscribers?</span>
<span id="cb8-96"><a href="#cb8-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-97"><a href="#cb8-97" aria-hidden="true" tabindex="-1"></a>To find out, we run an **A/B test**. Each time a new visitor lands on the homepage, we randomly assign them to see either CTA A or CTA B — like flipping a fair coin on every visit. Once we have gathered data from enough visitors, we compare the sign-up rates between the two groups. Randomization is the key ingredient: it ensures that any difference we observe in sign-up rates is attributable to the CTA itself, rather than to some confounding factor such as time of day, device type, or traffic source.</span>
<span id="cb8-98"><a href="#cb8-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-99"><a href="#cb8-99" aria-hidden="true" tabindex="-1"></a>In this post, we walk through the core ideas of classical frequentist statistics by working through this A/B test from the ground up — simulating data, visualizing the Law of Large Numbers, bootstrapping confidence intervals, demonstrating the Central Limit Theorem, performing a hypothesis test, connecting that test to linear regression, and finally showing what goes wrong when you peek at your results too early.</span>
<span id="cb8-100"><a href="#cb8-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-101"><a href="#cb8-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-102"><a href="#cb8-102" aria-hidden="true" tabindex="-1"></a><span class="fu">## The A/B Test as a Statistical Problem</span></span>
<span id="cb8-103"><a href="#cb8-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-104"><a href="#cb8-104" aria-hidden="true" tabindex="-1"></a>At the individual level, every visitor either signs up (outcome = 1) or does not (outcome = 0). This binary trial is exactly the setting modeled by a **Bernoulli distribution**: a single flip of a coin whose probability of heads is some unknown parameter $\pi$. We write:</span>
<span id="cb8-105"><a href="#cb8-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-106"><a href="#cb8-106" aria-hidden="true" tabindex="-1"></a>$$X_i^A \sim \text{Bernoulli}(\pi_A) \qquad X_i^B \sim \text{Bernoulli}(\pi_B)$$</span>
<span id="cb8-107"><a href="#cb8-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-108"><a href="#cb8-108" aria-hidden="true" tabindex="-1"></a>where $\pi_A$ and $\pi_B$ are the true (unknown) sign-up probabilities under each CTA. The whole purpose of the experiment is to learn about these parameters from data.</span>
<span id="cb8-109"><a href="#cb8-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-110"><a href="#cb8-110" aria-hidden="true" tabindex="-1"></a>The **quantity we care about** is the difference in sign-up rates:</span>
<span id="cb8-111"><a href="#cb8-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-112"><a href="#cb8-112" aria-hidden="true" tabindex="-1"></a>$$\theta = \pi_A - \pi_B$$</span>
<span id="cb8-113"><a href="#cb8-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-114"><a href="#cb8-114" aria-hidden="true" tabindex="-1"></a>If $\theta &gt; 0$, CTA A converts better; if $\theta &lt; 0$, CTA B wins; if $\theta = 0$, the choice of wording makes no difference.</span>
<span id="cb8-115"><a href="#cb8-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-116"><a href="#cb8-116" aria-hidden="true" tabindex="-1"></a>Since $\theta$ is unobservable, we estimate it with the **difference in sample proportions**:</span>
<span id="cb8-117"><a href="#cb8-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-118"><a href="#cb8-118" aria-hidden="true" tabindex="-1"></a>$$\hat\theta = \bar{X}_A - \bar{X}_B = \hat\pi_A - \hat\pi_B$$</span>
<span id="cb8-119"><a href="#cb8-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-120"><a href="#cb8-120" aria-hidden="true" tabindex="-1"></a>Because each observation is either 0 or 1, the sample mean is just the fraction of visitors who signed up — so the two expressions are identical. This estimator is our best guess at $\theta$ given the data we collect.</span>
<span id="cb8-121"><a href="#cb8-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-122"><a href="#cb8-122" aria-hidden="true" tabindex="-1"></a>The sections that follow explore how reliable this estimator is, how uncertain we should be about it, and how to use it to reach a statistically rigorous decision.</span>
<span id="cb8-123"><a href="#cb8-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-124"><a href="#cb8-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-125"><a href="#cb8-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## Simulating Data</span></span>
<span id="cb8-126"><a href="#cb8-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-127"><a href="#cb8-127" aria-hidden="true" tabindex="-1"></a>In a real experiment we would never know the true values of $\pi_A$ and $\pi_B$ — estimating them is precisely why we run the test. But for the purpose of this walkthrough, we set them ourselves so we can study how our estimator behaves when we know the ground truth.</span>
<span id="cb8-128"><a href="#cb8-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-129"><a href="#cb8-129" aria-hidden="true" tabindex="-1"></a>We assume:</span>
<span id="cb8-130"><a href="#cb8-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-131"><a href="#cb8-131" aria-hidden="true" tabindex="-1"></a>$$\pi_A = 0.22, \quad \pi_B = 0.18, \quad \theta = \pi_A - \pi_B = 0.04$$</span>
<span id="cb8-132"><a href="#cb8-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-133"><a href="#cb8-133" aria-hidden="true" tabindex="-1"></a>So CTA A has a genuine four-percentage-point advantage. We simulate 1,000 visitor outcomes for each group (2,000 total).</span>
<span id="cb8-134"><a href="#cb8-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-137"><a href="#cb8-137" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-138"><a href="#cb8-138" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb8-139"><a href="#cb8-139" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb8-140"><a href="#cb8-140" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-141"><a href="#cb8-141" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-142"><a href="#cb8-142" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb8-143"><a href="#cb8-143" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb8-144"><a href="#cb8-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-145"><a href="#cb8-145" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb8-146"><a href="#cb8-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-147"><a href="#cb8-147" aria-hidden="true" tabindex="-1"></a>pi_A       <span class="op">=</span> <span class="fl">0.22</span></span>
<span id="cb8-148"><a href="#cb8-148" aria-hidden="true" tabindex="-1"></a>pi_B       <span class="op">=</span> <span class="fl">0.18</span></span>
<span id="cb8-149"><a href="#cb8-149" aria-hidden="true" tabindex="-1"></a>true_theta <span class="op">=</span> pi_A <span class="op">-</span> pi_B   <span class="co"># 0.04</span></span>
<span id="cb8-150"><a href="#cb8-150" aria-hidden="true" tabindex="-1"></a>n          <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb8-151"><a href="#cb8-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-152"><a href="#cb8-152" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate visitor outcomes: 1 = signed up, 0 = did not</span></span>
<span id="cb8-153"><a href="#cb8-153" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_A, n)   <span class="co"># CTA A group</span></span>
<span id="cb8-154"><a href="#cb8-154" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_B, n)   <span class="co"># CTA B group</span></span>
<span id="cb8-155"><a href="#cb8-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-156"><a href="#cb8-156" aria-hidden="true" tabindex="-1"></a>pi_A_hat  <span class="op">=</span> A.mean()</span>
<span id="cb8-157"><a href="#cb8-157" aria-hidden="true" tabindex="-1"></a>pi_B_hat  <span class="op">=</span> B.mean()</span>
<span id="cb8-158"><a href="#cb8-158" aria-hidden="true" tabindex="-1"></a>theta_hat <span class="op">=</span> pi_A_hat <span class="op">-</span> pi_B_hat</span>
<span id="cb8-159"><a href="#cb8-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-160"><a href="#cb8-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-163"><a href="#cb8-163" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-164"><a href="#cb8-164" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-165"><a href="#cb8-165" aria-hidden="true" tabindex="-1"></a>sim_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb8-166"><a href="#cb8-166" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Group"</span>: [<span class="st">"CTA A"</span>, <span class="st">"CTA B"</span>, <span class="st">"Difference (θ̂)"</span>],</span>
<span id="cb8-167"><a href="#cb8-167" aria-hidden="true" tabindex="-1"></a>    <span class="st">"True Value"</span>: [<span class="ss">f"π_A = </span><span class="sc">{</span>pi_A<span class="sc">}</span><span class="ss">"</span>, <span class="ss">f"π_B = </span><span class="sc">{</span>pi_B<span class="sc">}</span><span class="ss">"</span>, <span class="ss">f"θ = </span><span class="sc">{</span>true_theta<span class="sc">}</span><span class="ss">"</span>],</span>
<span id="cb8-168"><a href="#cb8-168" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Observed in Simulation"</span>: [<span class="ss">f"</span><span class="sc">{</span>pi_A_hat<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>pi_B_hat<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>theta_hat<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb8-169"><a href="#cb8-169" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-170"><a href="#cb8-170" aria-hidden="true" tabindex="-1"></a>display(styled_table(sim_df, caption<span class="op">=</span><span class="st">"Simulated Data Summary"</span>))</span>
<span id="cb8-171"><a href="#cb8-171" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-172"><a href="#cb8-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-173"><a href="#cb8-173" aria-hidden="true" tabindex="-1"></a>Our estimate $\hat\theta \approx$ <span class="in">`{python} round(theta_hat, 4)`</span> lands close to the true value of 0.04. The sections below explore *why* we can trust it, *how precise* it is, and *when* it is large enough to be statistically significant.</span>
<span id="cb8-174"><a href="#cb8-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-175"><a href="#cb8-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-176"><a href="#cb8-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Law of Large Numbers</span></span>
<span id="cb8-177"><a href="#cb8-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-178"><a href="#cb8-178" aria-hidden="true" tabindex="-1"></a>How do we know that $\hat\theta = \bar{X}_A - \bar{X}_B$ is a sensible estimator of $\theta$? The mathematical guarantee comes from the **Law of Large Numbers (LLN)**: as the number of observations grows, the sample mean converges to the population mean. Since $\hat\pi_A \to \pi_A$ and $\hat\pi_B \to \pi_B$, it follows that $\hat\theta \to \theta$.</span>
<span id="cb8-179"><a href="#cb8-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-180"><a href="#cb8-180" aria-hidden="true" tabindex="-1"></a>The LLN is the foundational reason why running a *larger* experiment gives you a *more reliable* answer. But how fast does convergence happen? The plot below makes it concrete.</span>
<span id="cb8-181"><a href="#cb8-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-182"><a href="#cb8-182" aria-hidden="true" tabindex="-1"></a>We compute the **element-wise differences** between CTA A and CTA B draws and track the **running (cumulative) mean** as we add one observation at a time.</span>
<span id="cb8-183"><a href="#cb8-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-186"><a href="#cb8-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-187"><a href="#cb8-187" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb8-188"><a href="#cb8-188" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb8-189"><a href="#cb8-189" aria-hidden="true" tabindex="-1"></a><span class="co"># Element-wise differences between paired draws</span></span>
<span id="cb8-190"><a href="#cb8-190" aria-hidden="true" tabindex="-1"></a>diffs <span class="op">=</span> A <span class="op">-</span> B   <span class="co"># length-1000 vector</span></span>
<span id="cb8-191"><a href="#cb8-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-192"><a href="#cb8-192" aria-hidden="true" tabindex="-1"></a><span class="co"># Running mean: average of first 1, first 2, …, first 1000 differences</span></span>
<span id="cb8-193"><a href="#cb8-193" aria-hidden="true" tabindex="-1"></a>running_mean <span class="op">=</span> np.cumsum(diffs) <span class="op">/</span> np.arange(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb8-194"><a href="#cb8-194" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-195"><a href="#cb8-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-198"><a href="#cb8-198" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-199"><a href="#cb8-199" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb8-200"><a href="#cb8-200" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb8-201"><a href="#cb8-201" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-lln</span></span>
<span id="cb8-202"><a href="#cb8-202" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "The running mean starts noisy but settles toward the true θ = 0.04 as the sample grows."</span></span>
<span id="cb8-203"><a href="#cb8-203" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb8-204"><a href="#cb8-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-205"><a href="#cb8-205" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">4.5</span>))</span>
<span id="cb8-206"><a href="#cb8-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-207"><a href="#cb8-207" aria-hidden="true" tabindex="-1"></a>ax.plot(<span class="bu">range</span>(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>), running_mean,</span>
<span id="cb8-208"><a href="#cb8-208" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="fl">1.6</span>, alpha<span class="op">=</span><span class="fl">0.9</span>, label<span class="op">=</span><span class="vs">r"Running mean of </span><span class="dv">$</span><span class="vs">X_A - X_B</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb8-209"><a href="#cb8-209" aria-hidden="true" tabindex="-1"></a>ax.axhline(true_theta, color<span class="op">=</span>RED, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb8-210"><a href="#cb8-210" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"True θ = </span><span class="sc">{</span>true_theta<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-211"><a href="#cb8-211" aria-hidden="true" tabindex="-1"></a>ax.fill_between(<span class="bu">range</span>(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>),</span>
<span id="cb8-212"><a href="#cb8-212" aria-hidden="true" tabindex="-1"></a>                true_theta <span class="op">-</span> <span class="fl">0.015</span>, true_theta <span class="op">+</span> <span class="fl">0.015</span>,</span>
<span id="cb8-213"><a href="#cb8-213" aria-hidden="true" tabindex="-1"></a>                alpha<span class="op">=</span><span class="fl">0.12</span>, color<span class="op">=</span>RED)</span>
<span id="cb8-214"><a href="#cb8-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-215"><a href="#cb8-215" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Number of Observations"</span>)</span>
<span id="cb8-216"><a href="#cb8-216" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Running Mean of Differences"</span>)</span>
<span id="cb8-217"><a href="#cb8-217" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Law of Large Numbers: Convergence of $</span><span class="ch">\\</span><span class="st">hat{</span><span class="ch">\\</span><span class="st">theta}$ Toward the True $</span><span class="ch">\\</span><span class="st">theta$"</span>)</span>
<span id="cb8-218"><a href="#cb8-218" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">True</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb8-219"><a href="#cb8-219" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">1</span>, n)</span>
<span id="cb8-220"><a href="#cb8-220" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-221"><a href="#cb8-221" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-222"><a href="#cb8-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-223"><a href="#cb8-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-224"><a href="#cb8-224" aria-hidden="true" tabindex="-1"></a>The plot tells a clear story. With only a handful of observations the running mean swings wildly — a few lucky sign-ups in one group can send the estimate far from the truth. But as the sample grows, those fluctuations dampen. By around 200–300 observations the curve has largely settled near 0.04, and by 1,000 observations it is hugging the true value closely.</span>
<span id="cb8-225"><a href="#cb8-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-226"><a href="#cb8-226" aria-hidden="true" tabindex="-1"></a>This is the LLN in action: **more data means less noise**. It is the foundational reason why running a larger experiment gives a more reliable answer than running a small one.</span>
<span id="cb8-227"><a href="#cb8-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-228"><a href="#cb8-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-229"><a href="#cb8-229" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bootstrap Standard Errors</span></span>
<span id="cb8-230"><a href="#cb8-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-231"><a href="#cb8-231" aria-hidden="true" tabindex="-1"></a>The LLN tells us our estimator will eventually get close to the truth, but "eventually" is not a precision statement. A practicing analyst also needs a measure of **uncertainty**: how far from the truth is $\hat\theta$ likely to be with the sample we actually have?</span>
<span id="cb8-232"><a href="#cb8-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-233"><a href="#cb8-233" aria-hidden="true" tabindex="-1"></a>One elegant approach is the **bootstrap**. The idea is deceptively simple: if we could re-run our experiment many times under identical conditions, we could directly observe how much $\hat\theta$ varies from run to run. We cannot actually re-run the experiment, but we can *simulate* repeated experiments by **resampling with replacement** from the data we already have.</span>
<span id="cb8-234"><a href="#cb8-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-235"><a href="#cb8-235" aria-hidden="true" tabindex="-1"></a>The procedure:</span>
<span id="cb8-236"><a href="#cb8-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-237"><a href="#cb8-237" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Draw 1,000 samples with replacement from the CTA A data ($A^*$) and independently from the CTA B data ($B^*$).</span>
<span id="cb8-238"><a href="#cb8-238" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Compute $\hat\theta^* = \bar{X}_{A}^* - \bar{X}_{B}^*$ for that resample.</span>
<span id="cb8-239"><a href="#cb8-239" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Repeat 1,000 times.</span>
<span id="cb8-240"><a href="#cb8-240" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>The standard deviation of those 1,000 bootstrapped estimates is the **bootstrapped standard error**.</span>
<span id="cb8-241"><a href="#cb8-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-244"><a href="#cb8-244" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-245"><a href="#cb8-245" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb8-246"><a href="#cb8-246" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb8-247"><a href="#cb8-247" aria-hidden="true" tabindex="-1"></a>B_reps <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb8-248"><a href="#cb8-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-249"><a href="#cb8-249" aria-hidden="true" tabindex="-1"></a>boot_thetas <span class="op">=</span> np.array([</span>
<span id="cb8-250"><a href="#cb8-250" aria-hidden="true" tabindex="-1"></a>    np.random.choice(A, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>).mean() <span class="op">-</span></span>
<span id="cb8-251"><a href="#cb8-251" aria-hidden="true" tabindex="-1"></a>    np.random.choice(B, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>).mean()</span>
<span id="cb8-252"><a href="#cb8-252" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(B_reps)</span>
<span id="cb8-253"><a href="#cb8-253" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb8-254"><a href="#cb8-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-255"><a href="#cb8-255" aria-hidden="true" tabindex="-1"></a>se_boot <span class="op">=</span> boot_thetas.std()</span>
<span id="cb8-256"><a href="#cb8-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-257"><a href="#cb8-257" aria-hidden="true" tabindex="-1"></a><span class="co"># Closed-form analytical SE for difference in two independent proportions</span></span>
<span id="cb8-258"><a href="#cb8-258" aria-hidden="true" tabindex="-1"></a>se_analytical <span class="op">=</span> np.sqrt(</span>
<span id="cb8-259"><a href="#cb8-259" aria-hidden="true" tabindex="-1"></a>    pi_A_hat <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_A_hat) <span class="op">/</span> n <span class="op">+</span></span>
<span id="cb8-260"><a href="#cb8-260" aria-hidden="true" tabindex="-1"></a>    pi_B_hat <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_B_hat) <span class="op">/</span> n</span>
<span id="cb8-261"><a href="#cb8-261" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-262"><a href="#cb8-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-263"><a href="#cb8-263" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% confidence interval using the bootstrapped SE (normal approximation)</span></span>
<span id="cb8-264"><a href="#cb8-264" aria-hidden="true" tabindex="-1"></a>ci_lo_boot <span class="op">=</span> theta_hat <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se_boot</span>
<span id="cb8-265"><a href="#cb8-265" aria-hidden="true" tabindex="-1"></a>ci_hi_boot <span class="op">=</span> theta_hat <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se_boot</span>
<span id="cb8-266"><a href="#cb8-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-267"><a href="#cb8-267" aria-hidden="true" tabindex="-1"></a>ci_lo_anal <span class="op">=</span> theta_hat <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se_analytical</span>
<span id="cb8-268"><a href="#cb8-268" aria-hidden="true" tabindex="-1"></a>ci_hi_anal <span class="op">=</span> theta_hat <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se_analytical</span>
<span id="cb8-269"><a href="#cb8-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-270"><a href="#cb8-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-273"><a href="#cb8-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-274"><a href="#cb8-274" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-275"><a href="#cb8-275" aria-hidden="true" tabindex="-1"></a>se_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb8-276"><a href="#cb8-276" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Method"</span>: [<span class="st">"Bootstrap"</span>, <span class="st">"Analytical formula"</span>],</span>
<span id="cb8-277"><a href="#cb8-277" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Standard Error"</span>: [<span class="ss">f"</span><span class="sc">{</span>se_boot<span class="sc">:.5f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>se_analytical<span class="sc">:.5f}</span><span class="ss">"</span>],</span>
<span id="cb8-278"><a href="#cb8-278" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% CI Lower"</span>: [<span class="ss">f"</span><span class="sc">{</span>ci_lo_boot<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>ci_lo_anal<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb8-279"><a href="#cb8-279" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% CI Upper"</span>: [<span class="ss">f"</span><span class="sc">{</span>ci_hi_boot<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>ci_hi_anal<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb8-280"><a href="#cb8-280" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-281"><a href="#cb8-281" aria-hidden="true" tabindex="-1"></a>display(styled_table(se_df, caption<span class="op">=</span><span class="st">"Standard Error Comparison: Bootstrap vs. Analytical"</span>))</span>
<span id="cb8-282"><a href="#cb8-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-283"><a href="#cb8-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-284"><a href="#cb8-284" aria-hidden="true" tabindex="-1"></a>The two standard errors are nearly identical — which is exactly what we should hope to see. The bootstrap is recovering the same precision estimate as the closed-form formula, without requiring us to know that formula in advance. This is the real power of the bootstrap: **it works equally well regardless of how complicated your estimator is**.</span>
<span id="cb8-285"><a href="#cb8-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-286"><a href="#cb8-286" aria-hidden="true" tabindex="-1"></a>**Interpreting the confidence interval:** We are 95% confident that the true difference $\theta = \pi_A - \pi_B$ lies between <span class="in">`{python} round(ci_lo_boot, 4)`</span> and <span class="in">`{python} round(ci_hi_boot, 4)`</span>. Since this interval sits entirely above zero, it provides evidence that CTA A genuinely outperforms CTA B — and not merely by chance.</span>
<span id="cb8-287"><a href="#cb8-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-288"><a href="#cb8-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-289"><a href="#cb8-289" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Central Limit Theorem</span></span>
<span id="cb8-290"><a href="#cb8-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-291"><a href="#cb8-291" aria-hidden="true" tabindex="-1"></a>We now know our estimator converges (LLN) and that we can measure its variability (bootstrap). But to do formal hypothesis testing, we need to know the *shape* of the estimator's sampling distribution — not just its center and spread.</span>
<span id="cb8-292"><a href="#cb8-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-293"><a href="#cb8-293" aria-hidden="true" tabindex="-1"></a>The **Central Limit Theorem (CLT)** provides this. It states that regardless of what distribution the underlying data follow, the sampling distribution of the sample mean becomes approximately **Normal** as the sample size grows. Since $\hat\theta = \bar{X}_A - \bar{X}_B$ is the difference of two sample means — and the difference of two independent Normals is itself Normal — the CLT applies directly to our estimator.</span>
<span id="cb8-294"><a href="#cb8-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-295"><a href="#cb8-295" aria-hidden="true" tabindex="-1"></a>To see this in action, we simulate 1,000 experiments at each of four sample sizes, $n \in <span class="sc">\{</span>25, 50, 100, 500<span class="sc">\}</span>$, and plot the resulting distribution of $\hat\theta$.</span>
<span id="cb8-296"><a href="#cb8-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-299"><a href="#cb8-299" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-300"><a href="#cb8-300" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-301"><a href="#cb8-301" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-clt</span></span>
<span id="cb8-302"><a href="#cb8-302" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "As sample size grows, the sampling distribution of θ̂ becomes smoother and more bell-shaped. The dashed curve is the best-fit Normal; the red line marks the true θ = 0.04."</span></span>
<span id="cb8-303"><a href="#cb8-303" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">25</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>]</span>
<span id="cb8-304"><a href="#cb8-304" aria-hidden="true" tabindex="-1"></a>n_sim <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb8-305"><a href="#cb8-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-306"><a href="#cb8-306" aria-hidden="true" tabindex="-1"></a>sim_results <span class="op">=</span> {}</span>
<span id="cb8-307"><a href="#cb8-307" aria-hidden="true" tabindex="-1"></a>all_vals <span class="op">=</span> []</span>
<span id="cb8-308"><a href="#cb8-308" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ss <span class="kw">in</span> sample_sizes:</span>
<span id="cb8-309"><a href="#cb8-309" aria-hidden="true" tabindex="-1"></a>    thetas <span class="op">=</span> np.array([</span>
<span id="cb8-310"><a href="#cb8-310" aria-hidden="true" tabindex="-1"></a>        np.random.binomial(<span class="dv">1</span>, pi_A, ss).mean() <span class="op">-</span></span>
<span id="cb8-311"><a href="#cb8-311" aria-hidden="true" tabindex="-1"></a>        np.random.binomial(<span class="dv">1</span>, pi_B, ss).mean()</span>
<span id="cb8-312"><a href="#cb8-312" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_sim)</span>
<span id="cb8-313"><a href="#cb8-313" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb8-314"><a href="#cb8-314" aria-hidden="true" tabindex="-1"></a>    sim_results[ss] <span class="op">=</span> thetas</span>
<span id="cb8-315"><a href="#cb8-315" aria-hidden="true" tabindex="-1"></a>    all_vals.extend(thetas)</span>
<span id="cb8-316"><a href="#cb8-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-317"><a href="#cb8-317" aria-hidden="true" tabindex="-1"></a><span class="co"># Consistent x-axis across all panels</span></span>
<span id="cb8-318"><a href="#cb8-318" aria-hidden="true" tabindex="-1"></a>x_lo <span class="op">=</span> np.percentile(all_vals, <span class="fl">0.5</span>)</span>
<span id="cb8-319"><a href="#cb8-319" aria-hidden="true" tabindex="-1"></a>x_hi <span class="op">=</span> np.percentile(all_vals, <span class="fl">99.5</span>)</span>
<span id="cb8-320"><a href="#cb8-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-321"><a href="#cb8-321" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb8-322"><a href="#cb8-322" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb8-323"><a href="#cb8-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-324"><a href="#cb8-324" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, ss <span class="kw">in</span> <span class="bu">enumerate</span>(sample_sizes):</span>
<span id="cb8-325"><a href="#cb8-325" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axes[i]</span>
<span id="cb8-326"><a href="#cb8-326" aria-hidden="true" tabindex="-1"></a>    thetas <span class="op">=</span> sim_results[ss]</span>
<span id="cb8-327"><a href="#cb8-327" aria-hidden="true" tabindex="-1"></a>    mu, sigma <span class="op">=</span> thetas.mean(), thetas.std()</span>
<span id="cb8-328"><a href="#cb8-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-329"><a href="#cb8-329" aria-hidden="true" tabindex="-1"></a>    ax.hist(thetas, bins<span class="op">=</span><span class="dv">35</span>, density<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb8-330"><a href="#cb8-330" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span>PALETTE[i], alpha<span class="op">=</span><span class="fl">0.72</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>, lw<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb8-331"><a href="#cb8-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-332"><a href="#cb8-332" aria-hidden="true" tabindex="-1"></a>    x_range <span class="op">=</span> np.linspace(x_lo, x_hi, <span class="dv">300</span>)</span>
<span id="cb8-333"><a href="#cb8-333" aria-hidden="true" tabindex="-1"></a>    ax.plot(x_range, stats.norm.pdf(x_range, mu, sigma),</span>
<span id="cb8-334"><a href="#cb8-334" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="dv">2</span>, ls<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.85</span>, label<span class="op">=</span><span class="st">"Normal fit"</span>)</span>
<span id="cb8-335"><a href="#cb8-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-336"><a href="#cb8-336" aria-hidden="true" tabindex="-1"></a>    ax.axvline(true_theta, color<span class="op">=</span>RED, lw<span class="op">=</span><span class="fl">1.8</span>, ls<span class="op">=</span><span class="st">"-"</span>, alpha<span class="op">=</span><span class="fl">0.9</span>, label<span class="op">=</span><span class="st">"True θ = 0.04"</span>)</span>
<span id="cb8-337"><a href="#cb8-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-338"><a href="#cb8-338" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"n = </span><span class="sc">{</span>ss<span class="sc">}</span><span class="ss"> per group"</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb8-339"><a href="#cb8-339" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">hat{</span><span class="ch">\t</span><span class="vs">heta}</span><span class="dv">$</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb8-340"><a href="#cb8-340" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"Density"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb8-341"><a href="#cb8-341" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(x_lo, x_hi)</span>
<span id="cb8-342"><a href="#cb8-342" aria-hidden="true" tabindex="-1"></a>    ax.text(<span class="fl">0.97</span>, <span class="fl">0.93</span>, <span class="ss">f"SD = </span><span class="sc">{</span>sigma<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb8-343"><a href="#cb8-343" aria-hidden="true" tabindex="-1"></a>            ha<span class="op">=</span><span class="st">"right"</span>, va<span class="op">=</span><span class="st">"top"</span>, transform<span class="op">=</span>ax.transAxes, fontsize<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb8-344"><a href="#cb8-344" aria-hidden="true" tabindex="-1"></a>            bbox<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">"white"</span>, alpha<span class="op">=</span><span class="fl">0.8</span>, edgecolor<span class="op">=</span><span class="st">"none"</span>,</span>
<span id="cb8-345"><a href="#cb8-345" aria-hidden="true" tabindex="-1"></a>                      boxstyle<span class="op">=</span><span class="st">"round,pad=0.3"</span>))</span>
<span id="cb8-346"><a href="#cb8-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-347"><a href="#cb8-347" aria-hidden="true" tabindex="-1"></a>legend_elements <span class="op">=</span> [</span>
<span id="cb8-348"><a href="#cb8-348" aria-hidden="true" tabindex="-1"></a>    mpatches.Patch(facecolor<span class="op">=</span><span class="st">"gray"</span>, alpha<span class="op">=</span><span class="fl">0.65</span>, label<span class="op">=</span><span class="st">"Simulated distribution"</span>),</span>
<span id="cb8-349"><a href="#cb8-349" aria-hidden="true" tabindex="-1"></a>    Line2D([<span class="dv">0</span>], [<span class="dv">0</span>], color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="dv">2</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"Normal fit"</span>),</span>
<span id="cb8-350"><a href="#cb8-350" aria-hidden="true" tabindex="-1"></a>    Line2D([<span class="dv">0</span>], [<span class="dv">0</span>], color<span class="op">=</span>RED, lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="st">"True θ = 0.04"</span>),</span>
<span id="cb8-351"><a href="#cb8-351" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb8-352"><a href="#cb8-352" aria-hidden="true" tabindex="-1"></a>fig.legend(handles<span class="op">=</span>legend_elements, loc<span class="op">=</span><span class="st">"lower center"</span>, ncol<span class="op">=</span><span class="dv">3</span>, fontsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb8-353"><a href="#cb8-353" aria-hidden="true" tabindex="-1"></a>           bbox_to_anchor<span class="op">=</span>(<span class="fl">0.5</span>, <span class="op">-</span><span class="fl">0.03</span>), frameon<span class="op">=</span><span class="va">True</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb8-354"><a href="#cb8-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-355"><a href="#cb8-355" aria-hidden="true" tabindex="-1"></a>fig.suptitle(</span>
<span id="cb8-356"><a href="#cb8-356" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Central Limit Theorem: Sampling Distribution of $</span><span class="ch">\\</span><span class="st">hat{</span><span class="ch">\\</span><span class="st">theta}$ at Different Sample Sizes"</span>,</span>
<span id="cb8-357"><a href="#cb8-357" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">13</span>, y<span class="op">=</span><span class="fl">1.01</span></span>
<span id="cb8-358"><a href="#cb8-358" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-359"><a href="#cb8-359" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-360"><a href="#cb8-360" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-361"><a href="#cb8-361" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-362"><a href="#cb8-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-363"><a href="#cb8-363" aria-hidden="true" tabindex="-1"></a>The progression is striking. At $n = 25$, the histogram is lumpy and slightly asymmetric — with such small samples the discrete Bernoulli nature of the data is still visible. By $n = 100$, the distribution has smoothed out considerably and the Normal approximation (dashed curve) is already reasonable. At $n = 500$, the histogram is nearly indistinguishable from a true Normal distribution.</span>
<span id="cb8-364"><a href="#cb8-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-365"><a href="#cb8-365" aria-hidden="true" tabindex="-1"></a>Notice also that the spread shrinks as $n$ grows — the LLN and CLT working in tandem. Larger samples yield estimates that are both more accurate *and* more tightly concentrated around the truth. The CLT is what licenses us to use Normal-based formulas (z-statistics, p-values) for inference in the sections that follow.</span>
<span id="cb8-366"><a href="#cb8-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-367"><a href="#cb8-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-368"><a href="#cb8-368" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis Testing</span></span>
<span id="cb8-369"><a href="#cb8-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-370"><a href="#cb8-370" aria-hidden="true" tabindex="-1"></a>Now that we know $\hat\theta$ is approximately Normally distributed for large samples, we can ask the formal question: **Is the difference we observed large enough to rule out random chance?**</span>
<span id="cb8-371"><a href="#cb8-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-372"><a href="#cb8-372" aria-hidden="true" tabindex="-1"></a>This is the logic of **hypothesis testing**. We begin by assuming the most skeptical position — that there is no difference between the two CTAs — and ask whether the data are inconsistent with that assumption.</span>
<span id="cb8-373"><a href="#cb8-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-374"><a href="#cb8-374" aria-hidden="true" tabindex="-1"></a>$$H_0: \theta = 0 \quad \text{(no difference)} \qquad H_1: \theta \neq 0 \quad \text{(some difference)}$$</span>
<span id="cb8-375"><a href="#cb8-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-376"><a href="#cb8-376" aria-hidden="true" tabindex="-1"></a>Under $H_0$, the CLT tells us $\hat\theta \approx N(0, \text{SE}(\hat\theta))$. To assess how unusual our observed $\hat\theta$ is, we **standardize** it:</span>
<span id="cb8-377"><a href="#cb8-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-378"><a href="#cb8-378" aria-hidden="true" tabindex="-1"></a>$$z = \frac{\hat\theta - 0}{\text{SE}(\hat\theta)}$$</span>
<span id="cb8-379"><a href="#cb8-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-380"><a href="#cb8-380" aria-hidden="true" tabindex="-1"></a>After standardization, $z$ follows approximately a standard Normal $N(0, 1)$ under $H_0$. The **p-value** is the probability of observing a $|z|$ as large as ours (or larger) if the null were actually true. A small p-value means our data would be very surprising under $H_0$ — strong reason to doubt it.</span>
<span id="cb8-381"><a href="#cb8-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-382"><a href="#cb8-382" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Why "t-test" if we're using the Normal?** In the classical t-test, the data themselves are assumed Normal and the variance must be estimated — the resulting ratio then follows an exact t-distribution. Here, our data are Bernoulli (binary), so there is no exact t-distribution result. The CLT gives us approximate Normality, and what we are doing is technically a **z-test**. In practice, for large samples the t-distribution converges to the standard Normal, so the distinction rarely matters numerically — but it is important to understand conceptually why.</span></span>
<span id="cb8-383"><a href="#cb8-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-386"><a href="#cb8-386" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-387"><a href="#cb8-387" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb8-388"><a href="#cb8-388" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb8-389"><a href="#cb8-389" aria-hidden="true" tabindex="-1"></a>z_stat  <span class="op">=</span> theta_hat <span class="op">/</span> se_analytical</span>
<span id="cb8-390"><a href="#cb8-390" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(<span class="bu">abs</span>(z_stat)))</span>
<span id="cb8-391"><a href="#cb8-391" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-392"><a href="#cb8-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-395"><a href="#cb8-395" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-396"><a href="#cb8-396" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-397"><a href="#cb8-397" aria-hidden="true" tabindex="-1"></a>test_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb8-398"><a href="#cb8-398" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Quantity"</span>: [</span>
<span id="cb8-399"><a href="#cb8-399" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Estimated difference (θ̂)"</span>,</span>
<span id="cb8-400"><a href="#cb8-400" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Standard error SE(θ̂)"</span>,</span>
<span id="cb8-401"><a href="#cb8-401" aria-hidden="true" tabindex="-1"></a>        <span class="st">"z-statistic"</span>,</span>
<span id="cb8-402"><a href="#cb8-402" aria-hidden="true" tabindex="-1"></a>        <span class="st">"p-value"</span>,</span>
<span id="cb8-403"><a href="#cb8-403" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Significant at α = 0.05?"</span>,</span>
<span id="cb8-404"><a href="#cb8-404" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb8-405"><a href="#cb8-405" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>: [</span>
<span id="cb8-406"><a href="#cb8-406" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>theta_hat<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb8-407"><a href="#cb8-407" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>se_analytical<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb8-408"><a href="#cb8-408" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>z_stat<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb8-409"><a href="#cb8-409" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb8-410"><a href="#cb8-410" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Yes"</span> <span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"No"</span>,</span>
<span id="cb8-411"><a href="#cb8-411" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb8-412"><a href="#cb8-412" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-413"><a href="#cb8-413" aria-hidden="true" tabindex="-1"></a>display(styled_table(test_df, caption<span class="op">=</span><span class="st">"Two-Sample Z-Test Results"</span>))</span>
<span id="cb8-414"><a href="#cb8-414" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-415"><a href="#cb8-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-416"><a href="#cb8-416" aria-hidden="true" tabindex="-1"></a>With a p-value of <span class="in">`{python} round(p_value, 4)`</span> — well below the conventional 0.05 threshold — we **reject the null hypothesis**. The data provide strong statistical evidence that CTA A and CTA B produce different sign-up rates, confirming the four-percentage-point advantage we built into the simulation.</span>
<span id="cb8-417"><a href="#cb8-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-418"><a href="#cb8-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-419"><a href="#cb8-419" aria-hidden="true" tabindex="-1"></a><span class="fu">## The T-Test as a Regression</span></span>
<span id="cb8-420"><a href="#cb8-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-421"><a href="#cb8-421" aria-hidden="true" tabindex="-1"></a>There is an elegant algebraic fact hidden beneath the two-sample test: **it is mathematically equivalent to a simple linear regression**. Understanding this connection matters because the regression framework generalizes naturally — you can add control variables, interaction terms, or additional treatment arms — while producing identical inference in the simple two-group case.</span>
<span id="cb8-422"><a href="#cb8-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-423"><a href="#cb8-423" aria-hidden="true" tabindex="-1"></a>The setup is straightforward. We stack all 2,000 observations into a single dataset with two columns:</span>
<span id="cb8-424"><a href="#cb8-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-425"><a href="#cb8-425" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$Y_i$: 1 if visitor $i$ signed up, 0 otherwise</span>
<span id="cb8-426"><a href="#cb8-426" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$D_i$: 1 if visitor $i$ saw CTA A, 0 if they saw CTA B</span>
<span id="cb8-427"><a href="#cb8-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-428"><a href="#cb8-428" aria-hidden="true" tabindex="-1"></a>We then fit:</span>
<span id="cb8-429"><a href="#cb8-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-430"><a href="#cb8-430" aria-hidden="true" tabindex="-1"></a>$$Y_i = \beta_0 + \beta_1 D_i + \varepsilon_i$$</span>
<span id="cb8-431"><a href="#cb8-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-432"><a href="#cb8-432" aria-hidden="true" tabindex="-1"></a>The OLS estimates have an immediate interpretation:</span>
<span id="cb8-433"><a href="#cb8-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-434"><a href="#cb8-434" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\hat\beta_0$ is the expected $Y_i$ when $D_i = 0$ (CTA B) — i.e., $\hat\beta_0 = \hat\pi_B$.</span>
<span id="cb8-435"><a href="#cb8-435" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\hat\beta_0 + \hat\beta_1$ is the expected $Y_i$ when $D_i = 1$ (CTA A) — i.e., $\hat\beta_0 + \hat\beta_1 = \hat\pi_A$.</span>
<span id="cb8-436"><a href="#cb8-436" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Therefore $\hat\beta_1 = \hat\pi_A - \hat\pi_B = \hat\theta$ — numerically identical to our earlier estimator.</span>
<span id="cb8-437"><a href="#cb8-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-440"><a href="#cb8-440" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-441"><a href="#cb8-441" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb8-442"><a href="#cb8-442" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb8-443"><a href="#cb8-443" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> np.concatenate([A, B])</span>
<span id="cb8-444"><a href="#cb8-444" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> np.concatenate([np.ones(n), np.zeros(n)])   <span class="co"># 1 = CTA A, 0 = CTA B</span></span>
<span id="cb8-445"><a href="#cb8-445" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(D)</span>
<span id="cb8-446"><a href="#cb8-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-447"><a href="#cb8-447" aria-hidden="true" tabindex="-1"></a>ols_model <span class="op">=</span> sm.OLS(Y, X).fit()</span>
<span id="cb8-448"><a href="#cb8-448" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-449"><a href="#cb8-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-452"><a href="#cb8-452" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-453"><a href="#cb8-453" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-454"><a href="#cb8-454" aria-hidden="true" tabindex="-1"></a>coef_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb8-455"><a href="#cb8-455" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Term"</span>: [<span class="st">"Intercept  (β₀)"</span>, <span class="st">"CTA A Indicator  (β₁)"</span>],</span>
<span id="cb8-456"><a href="#cb8-456" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate"</span>: [<span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>params[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb8-457"><a href="#cb8-457" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Std. Error"</span>: [<span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>bse[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>bse[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb8-458"><a href="#cb8-458" aria-hidden="true" tabindex="-1"></a>    <span class="st">"t-statistic"</span>: [<span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>tvalues[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>tvalues[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb8-459"><a href="#cb8-459" aria-hidden="true" tabindex="-1"></a>    <span class="st">"p-value"</span>: [<span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>pvalues[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>ols_model<span class="sc">.</span>pvalues[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb8-460"><a href="#cb8-460" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-461"><a href="#cb8-461" aria-hidden="true" tabindex="-1"></a>display(styled_table(coef_df, caption<span class="op">=</span><span class="st">"OLS Regression Coefficients"</span>))</span>
<span id="cb8-462"><a href="#cb8-462" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-463"><a href="#cb8-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-464"><a href="#cb8-464" aria-hidden="true" tabindex="-1"></a>Look at the row for $\hat\beta_1$: the estimate, standard error, and p-value are essentially identical to the values we computed using the two-sample approach. The small numerical difference arises because standard OLS assumes a **pooled variance** across both groups, while our two-sample formula used **separate variance estimates** for each group. For large samples of equal size, the difference is negligible.</span>
<span id="cb8-465"><a href="#cb8-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-466"><a href="#cb8-466" aria-hidden="true" tabindex="-1"></a>The intercept $\hat\beta_0 \approx$ <span class="in">`{python} round(ols_model.params[0], 4)`</span> estimates $\pi_B$ (the CTA B sign-up rate), and $\hat\beta_0 + \hat\beta_1 \approx$ <span class="in">`{python} round(ols_model.params[0] + ols_model.params[1], 4)`</span> estimates $\pi_A$ — both very close to the true values of 0.18 and 0.22.</span>
<span id="cb8-467"><a href="#cb8-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-468"><a href="#cb8-468" aria-hidden="true" tabindex="-1"></a>The regression framework is therefore not just an alternative way to run the same test — it is the foundation for everything more complex that comes after.</span>
<span id="cb8-469"><a href="#cb8-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-470"><a href="#cb8-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-471"><a href="#cb8-471" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Problem with Peeking</span></span>
<span id="cb8-472"><a href="#cb8-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-473"><a href="#cb8-473" aria-hidden="true" tabindex="-1"></a>Everything we have done so far assumes the experiment runs to completion before we look at the results. But what if someone gets impatient?</span>
<span id="cb8-474"><a href="#cb8-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-475"><a href="#cb8-475" aria-hidden="true" tabindex="-1"></a>Suppose your boss wants to check in after every 100 visitors per group — at $n = 100, 200, \ldots, 1000$ — and declare a winner as soon as any single test comes back significant at $\alpha = 0.05$. This practice is called **peeking**, and it quietly destroys the statistical properties of the test.</span>
<span id="cb8-476"><a href="#cb8-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-477"><a href="#cb8-477" aria-hidden="true" tabindex="-1"></a>Here is why. A single test at $\alpha = 0.05$ has a 5% chance of a **false positive** — rejecting $H_0$ when it is actually true. But each peek at accumulating data creates another independent opportunity to get unlucky. The overall probability of at least one false positive across all 10 peeks is much higher than 5%, even if the two CTAs are genuinely identical.</span>
<span id="cb8-478"><a href="#cb8-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-479"><a href="#cb8-479" aria-hidden="true" tabindex="-1"></a>We can measure exactly how much higher with a simulation. We set up a world where **the null is true** ($\pi_A = \pi_B = 0.20$, no real difference), run 10,000 simulated experiments, and record in what fraction of those experiments peeking produces at least one spurious significant result.</span>
<span id="cb8-480"><a href="#cb8-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-483"><a href="#cb8-483" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-484"><a href="#cb8-484" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb8-485"><a href="#cb8-485" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb8-486"><a href="#cb8-486" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">123</span>)</span>
<span id="cb8-487"><a href="#cb8-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-488"><a href="#cb8-488" aria-hidden="true" tabindex="-1"></a>pi_null       <span class="op">=</span> <span class="fl">0.20</span></span>
<span id="cb8-489"><a href="#cb8-489" aria-hidden="true" tabindex="-1"></a>n_total       <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb8-490"><a href="#cb8-490" aria-hidden="true" tabindex="-1"></a>checkpoints   <span class="op">=</span> np.arange(<span class="dv">100</span>, <span class="dv">1001</span>, <span class="dv">100</span>)   <span class="co"># peek at 100, 200, …, 1000</span></span>
<span id="cb8-491"><a href="#cb8-491" aria-hidden="true" tabindex="-1"></a>n_experiments <span class="op">=</span> <span class="dv">10_000</span></span>
<span id="cb8-492"><a href="#cb8-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-493"><a href="#cb8-493" aria-hidden="true" tabindex="-1"></a>false_positives <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb8-494"><a href="#cb8-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-495"><a href="#cb8-495" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_experiments):</span>
<span id="cb8-496"><a href="#cb8-496" aria-hidden="true" tabindex="-1"></a>    A_null <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_null, n_total)</span>
<span id="cb8-497"><a href="#cb8-497" aria-hidden="true" tabindex="-1"></a>    B_null <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_null, n_total)</span>
<span id="cb8-498"><a href="#cb8-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-499"><a href="#cb8-499" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> cp <span class="kw">in</span> checkpoints:</span>
<span id="cb8-500"><a href="#cb8-500" aria-hidden="true" tabindex="-1"></a>        a_sub <span class="op">=</span> A_null[:cp]</span>
<span id="cb8-501"><a href="#cb8-501" aria-hidden="true" tabindex="-1"></a>        b_sub <span class="op">=</span> B_null[:cp]</span>
<span id="cb8-502"><a href="#cb8-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-503"><a href="#cb8-503" aria-hidden="true" tabindex="-1"></a>        pa <span class="op">=</span> a_sub.mean()</span>
<span id="cb8-504"><a href="#cb8-504" aria-hidden="true" tabindex="-1"></a>        pb <span class="op">=</span> b_sub.mean()</span>
<span id="cb8-505"><a href="#cb8-505" aria-hidden="true" tabindex="-1"></a>        diff <span class="op">=</span> pa <span class="op">-</span> pb</span>
<span id="cb8-506"><a href="#cb8-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-507"><a href="#cb8-507" aria-hidden="true" tabindex="-1"></a>        se_sub <span class="op">=</span> np.sqrt(pa <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pa) <span class="op">/</span> cp <span class="op">+</span> pb <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pb) <span class="op">/</span> cp)</span>
<span id="cb8-508"><a href="#cb8-508" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> se_sub <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb8-509"><a href="#cb8-509" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb8-510"><a href="#cb8-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-511"><a href="#cb8-511" aria-hidden="true" tabindex="-1"></a>        z_sub <span class="op">=</span> diff <span class="op">/</span> se_sub</span>
<span id="cb8-512"><a href="#cb8-512" aria-hidden="true" tabindex="-1"></a>        p_sub <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(<span class="bu">abs</span>(z_sub)))</span>
<span id="cb8-513"><a href="#cb8-513" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-514"><a href="#cb8-514" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p_sub <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb8-515"><a href="#cb8-515" aria-hidden="true" tabindex="-1"></a>            false_positives <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb8-516"><a href="#cb8-516" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span>   <span class="co"># boss declares a winner and stops the experiment</span></span>
<span id="cb8-517"><a href="#cb8-517" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-518"><a href="#cb8-518" aria-hidden="true" tabindex="-1"></a>fpr <span class="op">=</span> false_positives <span class="op">/</span> n_experiments</span>
<span id="cb8-519"><a href="#cb8-519" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-520"><a href="#cb8-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-523"><a href="#cb8-523" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-524"><a href="#cb8-524" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-525"><a href="#cb8-525" aria-hidden="true" tabindex="-1"></a>peek_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb8-526"><a href="#cb8-526" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Approach"</span>: [</span>
<span id="cb8-527"><a href="#cb8-527" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Single pre-planned test (correct practice)"</span>,</span>
<span id="cb8-528"><a href="#cb8-528" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Peek after every 100 visitors (10 peeks)"</span>,</span>
<span id="cb8-529"><a href="#cb8-529" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb8-530"><a href="#cb8-530" aria-hidden="true" tabindex="-1"></a>    <span class="st">"False Positive Rate"</span>: [<span class="st">"~5.0%"</span>, <span class="ss">f"~</span><span class="sc">{</span>fpr <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>],</span>
<span id="cb8-531"><a href="#cb8-531" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Inflation vs. Nominal"</span>: [<span class="st">"1.0×"</span>, <span class="ss">f"</span><span class="sc">{</span>fpr <span class="op">/</span> <span class="fl">0.05</span><span class="sc">:.1f}</span><span class="ss">×"</span>],</span>
<span id="cb8-532"><a href="#cb8-532" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-533"><a href="#cb8-533" aria-hidden="true" tabindex="-1"></a>display(styled_table(peek_df,</span>
<span id="cb8-534"><a href="#cb8-534" aria-hidden="true" tabindex="-1"></a>                     caption<span class="op">=</span><span class="st">"False Positive Rate: Single Test vs. Sequential Peeking"</span>,</span>
<span id="cb8-535"><a href="#cb8-535" aria-hidden="true" tabindex="-1"></a>                     hdr_color<span class="op">=</span><span class="st">"#c0392b"</span>))</span>
<span id="cb8-536"><a href="#cb8-536" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-537"><a href="#cb8-537" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-540"><a href="#cb8-540" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-541"><a href="#cb8-541" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-542"><a href="#cb8-542" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-peeking</span></span>
<span id="cb8-543"><a href="#cb8-543" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "A single pre-planned test holds the false positive rate at 5%. Sequential peeking inflates it to roughly 26% — more than five times the nominal level."</span></span>
<span id="cb8-544"><a href="#cb8-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-545"><a href="#cb8-545" aria-hidden="true" tabindex="-1"></a>labels  <span class="op">=</span> [<span class="st">"Single</span><span class="ch">\n</span><span class="st">pre-planned test"</span>, <span class="st">"Peek every</span><span class="ch">\n</span><span class="st">100 visitors</span><span class="ch">\n</span><span class="st">(10 peeks)"</span>]</span>
<span id="cb8-546"><a href="#cb8-546" aria-hidden="true" tabindex="-1"></a>heights <span class="op">=</span> [<span class="fl">0.05</span>, fpr]</span>
<span id="cb8-547"><a href="#cb8-547" aria-hidden="true" tabindex="-1"></a>colors_ <span class="op">=</span> [GREEN, RED]</span>
<span id="cb8-548"><a href="#cb8-548" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-549"><a href="#cb8-549" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">4.5</span>))</span>
<span id="cb8-550"><a href="#cb8-550" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.bar(labels, heights, color<span class="op">=</span>colors_, width<span class="op">=</span><span class="fl">0.4</span>,</span>
<span id="cb8-551"><a href="#cb8-551" aria-hidden="true" tabindex="-1"></a>              edgecolor<span class="op">=</span><span class="st">"white"</span>, lw<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb8-552"><a href="#cb8-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-553"><a href="#cb8-553" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.05</span>, color<span class="op">=</span><span class="st">"gray"</span>, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.8</span>, label<span class="op">=</span><span class="st">"Nominal α = 5%"</span>)</span>
<span id="cb8-554"><a href="#cb8-554" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Empirical False Positive Rate"</span>)</span>
<span id="cb8-555"><a href="#cb8-555" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"How Peeking Inflates the Type I Error Rate"</span>)</span>
<span id="cb8-556"><a href="#cb8-556" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="bu">max</span>(heights) <span class="op">*</span> <span class="fl">1.25</span>)</span>
<span id="cb8-557"><a href="#cb8-557" aria-hidden="true" tabindex="-1"></a>ax.yaxis.set_major_formatter(plt.FuncFormatter(<span class="kw">lambda</span> y, _: <span class="ss">f"</span><span class="sc">{</span>y<span class="sc">:.0%}</span><span class="ss">"</span>))</span>
<span id="cb8-558"><a href="#cb8-558" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-559"><a href="#cb8-559" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar, h <span class="kw">in</span> <span class="bu">zip</span>(bars, heights):</span>
<span id="cb8-560"><a href="#cb8-560" aria-hidden="true" tabindex="-1"></a>    ax.text(bar.get_x() <span class="op">+</span> bar.get_width() <span class="op">/</span> <span class="dv">2</span>, h <span class="op">+</span> <span class="fl">0.005</span>,</span>
<span id="cb8-561"><a href="#cb8-561" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span>h<span class="sc">:.1%}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"bottom"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb8-562"><a href="#cb8-562" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-563"><a href="#cb8-563" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-564"><a href="#cb8-564" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-565"><a href="#cb8-565" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-566"><a href="#cb8-566" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-567"><a href="#cb8-567" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-568"><a href="#cb8-568" aria-hidden="true" tabindex="-1"></a>With 10 peeks, the false positive rate balloons to roughly **`{python} f"{fpr*100:.0f}"`%** — more than five times the nominal 5%. That means more than one in four experiments produces a false alarm, even when the two CTAs are absolutely identical in effectiveness.</span>
<span id="cb8-569"><a href="#cb8-569" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-570"><a href="#cb8-570" aria-hidden="true" tabindex="-1"></a>This is not a subtle theoretical quirk. It is a practical pitfall that has led to real-world product decisions being made on illusory results. The standard remedies include:</span>
<span id="cb8-571"><a href="#cb8-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-572"><a href="#cb8-572" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Pre-registering** your sample size and running exactly one final test,</span>
<span id="cb8-573"><a href="#cb8-573" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Using **sequential testing** methods (such as the Bonferroni correction or alpha-spending functions) that are designed to allow interim looks while still controlling the false positive rate, or</span>
<span id="cb8-574"><a href="#cb8-574" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Adopting a **Bayesian** framework, which naturally incorporates accumulating evidence without inflating Type I error.</span>
<span id="cb8-575"><a href="#cb8-575" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-576"><a href="#cb8-576" aria-hidden="true" tabindex="-1"></a>The bottom line: in frequentist A/B testing, a p-value only means what it says — a 5% false positive rate — if you decide the sample size in advance and run the test exactly once. Everything else is a departure from that guarantee, and the consequences can be severe.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Mo Boroumand</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/moboroumand">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/moboroumand">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>